version: '3.7'
services:
  python:
    image: feat/python:1.0
    build: ./python
    container_name: 'feat_python'
    working_dir: '/tmp/work'
    volumes:
      - type: bind
        source: ../python
        target: /tmp/work
    stdin_open: true
    tty: true